# Generated by Django 5.2.16 on 2026-07-21 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('general', 'Demande générale'), ('audit', 'Audit & Conseil'), ('formation', 'Formation & Workshop'), ('pentest', 'Pentesting'), ('developpement', "Développement d'application"), ('partenariat', 'Partenariat')], default='general', max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('topic', models.CharField(choices=[('all', 'Tous les sujets'), ('cybersecurity', 'Cybersécurité'), ('digital', 'Transformation digitale'), ('opportunities', 'Opportunités')], default='all', max_length=50)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
